export const quotes = [
  {
    q: "There is no fear for one whose mind is not filled with desires.",
    a: "Buddha",
    c: "63",
    h: "<blockquote>&ldquo;There is no fear for one whose mind is not filled with desires.&rdquo; &mdash; <footer>Buddha</footer></blockquote>",
  },
  {
    q: "Persistence is very important. You should not give up unless you are forced to give up.",
    a: "Elon Musk",
    c: "87",
    h: "<blockquote>&ldquo;Persistence is very important. You should not give up unless you are forced to give up.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "Honor is the foundation of courage.",
    a: "Amelia Earhart",
    c: "35",
    h: "<blockquote>&ldquo;Honor is the foundation of courage.&rdquo; &mdash; <footer>Amelia Earhart</footer></blockquote>",
  },
  {
    q: "Ponder and deliberate before you make a move.",
    a: "Sun Tzu",
    c: "45",
    h: "<blockquote>&ldquo;Ponder and deliberate before you make a move.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
  },
  {
    q: "Tradition is the illusion of permanence. ",
    a: "Woody Allen",
    c: "41",
    h: "<blockquote>&ldquo;Tradition is the illusion of permanence. &rdquo; &mdash; <footer>Woody Allen</footer></blockquote>",
  },
  {
    q: "The ability to observe without evaluating is the highest form of intelligence.",
    a: "Jiddu Krishnamurti",
    c: "78",
    h: "<blockquote>&ldquo;The ability to observe without evaluating is the highest form of intelligence.&rdquo; &mdash; <footer>Jiddu Krishnamurti</footer></blockquote>",
  },
  {
    q: "Giving is the secret of a healthy life. Not necessarily money, but whatever a person has of encouragement, sympathy and understanding.",
    a: "John D. Rockefeller",
    c: "134",
    h: "<blockquote>&ldquo;Giving is the secret of a healthy life. Not necessarily money, but whatever a person has of encouragement, sympathy and understanding.&rdquo; &mdash; <footer>John D. Rockefeller</footer></blockquote>",
  },
  {
    q: "It is not that we have too little time to do all the things we need to do , it is that we feel the need to do too many things in the time we have.",
    a: "Gary Keller",
    c: "146",
    h: "<blockquote>&ldquo;It is not that we have too little time to do all the things we need to do , it is that we feel the need to do too many things in the time we have.&rdquo; &mdash; <footer>Gary Keller</footer></blockquote>",
  },
  {
    q: "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.  ",
    a: "Seneca",
    c: "117",
    h: "<blockquote>&ldquo;It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.  &rdquo; &mdash; <footer>Seneca</footer></blockquote>",
  },
  {
    q: "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.",
    a: "Eleanor Roosevelt",
    c: "112",
    h: "<blockquote>&ldquo;You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more.",
    a: "Tony Robbins",
    c: "120",
    h: "<blockquote>&ldquo;Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "A man should never be ashamed to own that he has been in the wrong, which is but saying, that he is wiser today than yesterday.",
    a: "Jonathan Swift",
    c: "127",
    h: "<blockquote>&ldquo;A man should never be ashamed to own that he has been in the wrong, which is but saying, that he is wiser today than yesterday.&rdquo; &mdash; <footer>Jonathan Swift</footer></blockquote>",
  },
  {
    q: "Happiness is not something ready made. It comes from your own actions.",
    a: "Dalai Lama",
    c: "70",
    h: "<blockquote>&ldquo;Happiness is not something ready made. It comes from your own actions.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "Do not stop thinking of life as an adventure.",
    a: "Eleanor Roosevelt",
    c: "45",
    h: "<blockquote>&ldquo;Do not stop thinking of life as an adventure.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "New beginnings are disguised as painful endings.",
    a: "Lao Tzu",
    c: "48",
    h: "<blockquote>&ldquo;New beginnings are disguised as painful endings.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Creative people are often found either disagreeable or intimidating by mediocrities.",
    a: "Criss Jami",
    c: "84",
    h: "<blockquote>&ldquo;Creative people are often found either disagreeable or intimidating by mediocrities.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "Common sense is not so common. ",
    a: "Voltaire",
    c: "31",
    h: "<blockquote>&ldquo;Common sense is not so common. &rdquo; &mdash; <footer>Voltaire</footer></blockquote>",
  },
  {
    q: "All men who have achieved great things have been great dreamers. ",
    a: "Orison Swett Marden",
    c: "65",
    h: "<blockquote>&ldquo;All men who have achieved great things have been great dreamers. &rdquo; &mdash; <footer>Orison Swett Marden</footer></blockquote>",
  },
  {
    q: "If light is in your heart, you will find your way home.  ",
    a: "Rumi",
    c: "57",
    h: "<blockquote>&ldquo;If light is in your heart, you will find your way home.  &rdquo; &mdash; <footer>Rumi</footer></blockquote>",
  },
  {
    q: "Always keep your eyes open. Keep watching. Because whatever you see can inspire you.",
    a: "Grace Coddington",
    c: "84",
    h: "<blockquote>&ldquo;Always keep your eyes open. Keep watching. Because whatever you see can inspire you.&rdquo; &mdash; <footer>Grace Coddington</footer></blockquote>",
  },
  {
    q: "Just as true humor is laughter at oneself, true humanity is knowledge of oneself.",
    a: "Alan Watts",
    c: "81",
    h: "<blockquote>&ldquo;Just as true humor is laughter at oneself, true humanity is knowledge of oneself.&rdquo; &mdash; <footer>Alan Watts</footer></blockquote>",
  },
  {
    q: "You can have the mind or you can have the moment.",
    a: "Naval Ravikant",
    c: "49",
    h: "<blockquote>&ldquo;You can have the mind or you can have the moment.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
  },
  {
    q: "The important thing is not what one is born with but what use one makes of that equipment.",
    a: "Alfred Adler",
    c: "90",
    h: "<blockquote>&ldquo;The important thing is not what one is born with but what use one makes of that equipment.&rdquo; &mdash; <footer>Alfred Adler</footer></blockquote>",
  },
  {
    q: "Make yourself so useful to other people, that they think you are irreplaceable.",
    a: "Og Mandino",
    c: "79",
    h: "<blockquote>&ldquo;Make yourself so useful to other people, that they think you are irreplaceable.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Every second you have on this planet is very precious and it's your responsibility that you're happy.",
    a: "Naval Ravikant",
    c: "101",
    h: "<blockquote>&ldquo;Every second you have on this planet is very precious and it's your responsibility that you're happy.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
  },
  {
    q: "If you think you can do a thing or think you can't do a thing, you're right.",
    a: "Henry Ford",
    c: "76",
    h: "<blockquote>&ldquo;If you think you can do a thing or think you can't do a thing, you're right.&rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "If you take responsibility for yourself you will develop a hunger to accomplish your dream.",
    a: "Les Brown",
    c: "91",
    h: "<blockquote>&ldquo;If you take responsibility for yourself you will develop a hunger to accomplish your dream.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "Fools talk, cowards are silent, wise men listen.",
    a: "Carlos Ruiz Zafon",
    c: "48",
    h: "<blockquote>&ldquo;Fools talk, cowards are silent, wise men listen.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "To do two things at once is to do neither.",
    a: "Publilius Syrus",
    c: "42",
    h: "<blockquote>&ldquo;To do two things at once is to do neither.&rdquo; &mdash; <footer>Publilius Syrus</footer></blockquote>",
  },
  {
    q: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    a: "Henry David Thoreau",
    c: "100",
    h: "<blockquote>&ldquo;What you get by achieving your goals is not as important as what you become by achieving your goals.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "Whatever your mind can conceive and believe, it can achieve.",
    a: "Napoleon Hill",
    c: "60",
    h: "<blockquote>&ldquo;Whatever your mind can conceive and believe, it can achieve.&rdquo; &mdash; <footer>Napoleon Hill</footer></blockquote>",
  },
  {
    q: "We have to live life with a sense of urgency so not a minute is wasted.",
    a: "Les Brown",
    c: "71",
    h: "<blockquote>&ldquo;We have to live life with a sense of urgency so not a minute is wasted.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
  },
  {
    q: "Don't bother people for help without first trying to solve the problem yourself.",
    a: "Colin Powell",
    c: "80",
    h: "<blockquote>&ldquo;Don't bother people for help without first trying to solve the problem yourself.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>",
  },
  {
    q: "Conquer the devils with a little thing called love.",
    a: "Bob Marley",
    c: "51",
    h: "<blockquote>&ldquo;Conquer the devils with a little thing called love.&rdquo; &mdash; <footer>Bob Marley</footer></blockquote>",
  },
  {
    q: "What's right is what's left if you do everything else wrong.",
    a: "Robin Williams",
    c: "60",
    h: "<blockquote>&ldquo;What's right is what's left if you do everything else wrong.&rdquo; &mdash; <footer>Robin Williams</footer></blockquote>",
  },
  {
    q: "Sometimes success isn't about making the right decision, it's more about making some decision.",
    a: "Robin Sharma",
    c: "94",
    h: "<blockquote>&ldquo;Sometimes success isn't about making the right decision, it's more about making some decision.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Just get out and do it. You will be very, very glad that you did.",
    a: "Christopher McCandless",
    c: "65",
    h: "<blockquote>&ldquo;Just get out and do it. You will be very, very glad that you did.&rdquo; &mdash; <footer>Christopher McCandless</footer></blockquote>",
  },
  {
    q: "Never let the fear of striking out keep you from playing the game.",
    a: "Babe Ruth",
    c: "66",
    h: "<blockquote>&ldquo;Never let the fear of striking out keep you from playing the game.&rdquo; &mdash; <footer>Babe Ruth</footer></blockquote>",
  },
  {
    q: "Little by little, one travels far.",
    a: "J.R.R. Tolkien",
    c: "34",
    h: "<blockquote>&ldquo;Little by little, one travels far.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
  },
  {
    q: "The clock indicates the moment...but what does eternity indicate?",
    a: "Walt Whitman",
    c: "65",
    h: "<blockquote>&ldquo;The clock indicates the moment...but what does eternity indicate?&rdquo; &mdash; <footer>Walt Whitman</footer></blockquote>",
  },
  {
    q: "Success is often achieved by those who don't know that failure is inevitable.",
    a: "Coco Chanel",
    c: "77",
    h: "<blockquote>&ldquo;Success is often achieved by those who don't know that failure is inevitable.&rdquo; &mdash; <footer>Coco Chanel</footer></blockquote>",
  },
  {
    q: "If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.",
    a: "Pema Chodron",
    c: "100",
    h: "<blockquote>&ldquo;If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.&rdquo; &mdash; <footer>Pema Chodron</footer></blockquote>",
  },
  {
    q: "Where does a thought go when it's forgotten?",
    a: "Sigmund Freud",
    c: "44",
    h: "<blockquote>&ldquo;Where does a thought go when it's forgotten?&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    a: "Ralph Waldo Emerson",
    c: "93",
    h: "<blockquote>&ldquo;What lies behind us and what lies before us are tiny matters compared to what lies within us.&rdquo; &mdash; <footer>Ralph Waldo Emerson</footer></blockquote>",
  },
  {
    q: "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    a: "Maya Angelou",
    c: "119",
    h: "<blockquote>&ldquo;People will forget what you said, people will forget what you did, but people will never forget how you made them feel.&rdquo; &mdash; <footer>Maya Angelou</footer></blockquote>",
  },
  {
    q: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. ",
    a: "Henry Ford",
    c: "115",
    h: "<blockquote>&ldquo;When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. &rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "The best way to not feel hopeless is to get up and do something.",
    a: "Barack Obama",
    c: "64",
    h: "<blockquote>&ldquo;The best way to not feel hopeless is to get up and do something.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>",
  },
  {
    q: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    a: "Brian Tracy",
    c: "100",
    h: "<blockquote>&ldquo;You have within you right now, everything you need to deal with whatever the world can throw at you.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    a: "Roy T. Bennett",
    c: "85",
    h: "<blockquote>&ldquo;Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.",
    a: "Dalai Lama",
    c: "89",
    h: "<blockquote>&ldquo;Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
];
